title: 'People identity details '
description: 'I want to learn how to people''s identity with phone number '
steps:
  - course: githubtraining/introduction-to-github
    description: The first step in your course
  - link: 'https://lab.github.com'
    title: Check out Learning Lab for more courses!
    description: >-
      There are many more courses available on Learning Lab for you to check
      out.
